In [1]:
import csv
import pandas as pd
import numpy as np

In [3]:
patients = pd.read_csv("C:/Users/Ay/OneDrive - Institut Teknologi Sepuluh Nopember/Tesis/Patients/patients.csv", 
                  error_bad_lines=False,sep=',', encoding = 'utf-8')

In [5]:
patients

,subject_id,age,age_group,gender,issmoking,isconsumingalcohol,diabetic
0,2,0.0,baby,M,NaN,NaN,NaN
1,5,0.0,baby,M,NaN,NaN,NaN
2,6,66.0,adult,F,NaN,True,NaN
3,7,0.0,baby,F,NaN,NaN,NaN
4,8,0.0,baby,M,NaN,NaN,NaN
5,9,42.0,adult,M,NaN,NaN,NaN
6,10,0.0,baby,F,NaN,NaN,NaN
7,11,50.0,adult,F,NaN,NaN,NaN
8,12,72.0,adult,M,NaN,NaN,NaN
9,13,40.0,adult,F,NaN,NaN,NaN
10,16,0.0,baby,M,NaN,NaN,NaN
11,18,51.0,adult,NaN,NaN,NaN,NaN
12,19,100.0,>89,M,NaN,NaN,NaN
13,20,76.0,adult,F,NaN,NaN,NaN
14,22,65.0,adult,F,NaN,True,NaN
15,24,39.0,adult,M,True,NaN,NaN
16,25,59.0,adult,M,NaN,True,NaN
17,26,72.0,adult,M,True,True,NaN
18,27,0.0,baby,F,NaN,NaN,NaN
19,28,74.0,adult,M,NaN,NaN,NaN
20,30,100.0,>89,M,NaN,True,NaN
21,31,72.0,adult,M,NaN,True,NaN
22,32,46.0,adult,M,NaN,NaN,NaN
23,33,82.0,adult,M,NaN,NaN,NaN
24,35,69.0,adult,F,NaN,NaN,NaN
25,37,69.0,adult,M,NaN,True,NaN
26,38,76.0,adult,M,NaN,NaN,True
27,39,0.0,baby,F,NaN,NaN,NaN
28,41,57.0,adult,M,True,NaN,NaN
29,42,61.0,adult,M,NaN,NaN,NaN
...,...,...,...,...,...,...,...
38087,99868,20.0,adult,F,NaN,True,NaN
38088,99872,55.0,adult,F,NaN,NaN,NaN
38089,99873,46.0,adult,M,NaN,NaN,NaN
38090,99880,88.0,adult,F,NaN,NaN,NaN
38091,99881,78.0,adult,NaN,NaN,NaN,NaN
38092,99893,NaN,adult,M,NaN,NaN,NaN
38093,99894,60.0,adult,F,NaN,NaN,NaN
38094,99899,87.0,adult,M,True,NaN,NaN
38095,99901,69.0,adult,M,NaN,True,NaN
38096,99903,50.0,adult,M,NaN,NaN,NaN
38097,99912,85.0,adult,M,True,True,NaN
38098,99913,71.0,adult,M,NaN,True,True
38099,99922,69.0,adult,M,NaN,NaN,NaN
38100,99928,21.0,adult,F,NaN,NaN,True
38101,99934,18.0,adult,M,NaN,NaN,NaN
38102,99935,76.0,adult,M,NaN,NaN,NaN
38103,99936,100.0,>89,F,NaN,NaN,NaN
38104,99937,66.0,adult,F,True,NaN,NaN
38105,99944,85.0,adult,F,NaN,NaN,True
38106,99946,50.0,adult,M,NaN,True,NaN
38107,99955,63.0,adult,M,NaN,NaN,NaN
38108,99957,68.0,adult,NaN,NaN,NaN,True
38109,99965,66.0,adult,M,NaN,NaN,NaN
38110,99966,77.0,adult,M,True,NaN,NaN
38111,99973,65.0,adult,NaN,NaN,NaN,NaN
38112,99983,79.0,adult,M,NaN,NaN,True
38113,99985,54.0,adult,M,NaN,NaN,NaN
38114,99991,48.0,adult,M,NaN,True,NaN
38115,99992,66.0,adult,F,NaN,NaN,NaN
38116,99995,NaN,adult,F,True,NaN,NaN

In [10]:
patient = patients["diabetic"]
falsepatient = patient.isna().sum()
percentfalsepatient= falsepatient / len (patients)
percentfalsepatient

0.952698271112627

In [11]:
truepatient = len (patients) - falsepatient
percenttruepatient= truepatient / len (patients)
percenttruepatient

0.047301728887373086